### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by baiwe** [PierreMasselot/2017---Nonparametric-L-moment-homogeneity-test#1]
Hi, following the Example in `help.md`, we got the following problem. We have debugged a long time but do not solve it. I do not know if you got this problem. Please help me with this. Thanks a lot.

```R
> Lmom.homog.test(Maxwind)
[1] "Performing the Hosking-Wallis test with 1 variables."
 Error: $ operator is invalid for atomic vectors
4.is.kap(para)
3.are.parkap.valid(para)
2.quakap(Usim[, j], paramKappa[j, ]) at mew.R#72
1.Lmom.homog.test(Maxwind)
```

**Comment by PierreMasselot** [comment]
Hi, thanks for letting me know.

It was due to a conflict between two `quakap` functions: the one from `lmom` package and the one from `lmomco` packages. I have resolved it and now it should work. 
Let me know if not.
